#!/bin/sh

REPO=$1
START=$2
END=$3

LAYERS="meta-fsl-arm meta-fsl-arm-extra meta-fsl-demos base Documentation"
CWD=`pwd`

for l in $LAYERS; do
	(cd $REPO/sources/$l ; git log -p -M $START..$END | \
		python $CWD/../gitdm -b $CWD/ -c $CWD/gitdm.config -u -s -a -o $CWD/results.$l.txt -x $CWD/data.$l.csv)
done

rm -f $CWD/results.all.txt
rm -f $CWD/contributors.all.txt.in
for l in $LAYERS; do
	cat >> $CWD/results.all.txt <<EOF
Statistics for $l
$(for c in `seq 2 $(echo "Statistics for $l" | wc -c)`; do echo -n '-'; done)

$(cat results.$l.txt)


EOF
	tail -n +2 $CWD/data.$l.csv | cut -d ',' -f 1,2 | sed 's@"\(.*\)","\(.*\)"@\1 <\2>@g' >> $CWD/contributors.all.txt.in
	rm $CWD/results.$l.txt
	rm $CWD/data.$l.csv
done

sort -u < $CWD/contributors.all.txt.in > $CWD/contributors.all.txt
rm $CWD/contributors.all.txt.in
